<?xml version="1.0"?>
<package format="3">
  <name>rqt_crtk</name>
  <version>0.1.0</version>
  <description>Generic ROS 2 rqt plugins for CRTK devices.</description>
  <maintainer email="support@intusurg.com">dVRK maintainers</maintainer>
  <license>BSD-3-Clause</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>crtk_python_client</exec_depend>
  <exec_depend>diagnostic_msgs</exec_depend>
  <exec_depend>dvrk_simulator_base</exec_depend>
  <exec_depend>python_qt_binding</exec_depend>
  <exec_depend>rqt_gui</exec_depend>
  <exec_depend>rqt_gui_py</exec_depend>
  <export><build_type>ament_python</build_type><rqt_gui plugin="${prefix}/plugin.xml"/></export>
</package>
